# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12ed971036af187d22adbdead8891a0738ddc9d09e27d5cd92271c8e26ba09dba3b89429fe5eb0c9ae75a530cf3ffef6064b1b4afefab8f514772a2c7162f269

test:
  secret_key_base: 4f0956d4ed821167efb78e0205e662e5b6900338670505c7ce39cf3036f4912911deb1ef6353b21250fdea6272ba715ca23055b228ae146c38e566ceb3cfc098

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
